const Products = [
  {
    id: 1,
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with adjustable DPI.",
    price: 25.99,
    category: "Electronics",
    inStock: true,
  },
  {
    id: 2,
    name: "Bluetooth Speaker",
    description: "Portable speaker with rich bass and 12-hour battery life.",
    price: 45.5,
    category: "Electronics",
    inStock: true,
  },
  {
    id: 3,
    name: "Laptop Stand",
    description: "Aluminum stand suitable for all laptops.",
    price: 30,
    category: "Accessories",
    inStock: true,
  },
  {
    id: 4,
    name: "Notebook",
    description: "Hardcover ruled notebook with 200 pages.",
    price: 6.99,
    category: "Stationery",
    inStock: true,
  },
  {
    id: 5,
    name: "USB-C Cable",
    description: "1 meter long fast charging USB-C cable.",
    price: 8.5,
    category: "Electronics",
    inStock: false,
  },
  {
    id: 6,
    name: "Gaming Keyboard",
    description: "RGB mechanical keyboard with blue switches.",
    price: 59.99,
    category: "Electronics",
    inStock: true,
  },
  {
    id: 7,
    name: "Desk Lamp",
    description: "LED desk lamp with 5 brightness levels.",
    price: 22.45,
    category: "Furniture",
    inStock: true,
  },
  {
    id: 8,
    name: "Wireless Earbuds",
    description: "In-ear earbuds with noise cancellation and charging case.",
    price: 39.95,
    category: "Electronics",
    inStock: false,
  },
  {
    id: 9,
    name: "Water Bottle",
    description:
      "Stainless steel bottle, 750ml, keeps liquids cold for 24 hours.",
    price: 19.99,
    category: "Outdoors",
    inStock: true,
  },
  {
    id: 10,
    name: "Yoga Mat",
    description: "Non-slip exercise mat, 6mm thick.",
    price: 24,
    category: "Fitness",
    inStock: true,
  },
  {
    id: 11,
    name: "Smart Watch",
    description: "Track fitness, receive calls and messages.",
    price: 120,
    category: "Electronics",
    inStock: true,
  },
  {
    id: 12,
    name: "Coffee Mug",
    description: "Ceramic mug, 350ml with a fun design.",
    price: 12.5,
    category: "Kitchen",
    inStock: true,
  },
  {
    id: 13,
    name: "Backpack",
    description: "Water-resistant backpack with 3 compartments.",
    price: 49.99,
    category: "Bags",
    inStock: false,
  },
  {
    id: 14,
    name: "Phone Holder",
    description: "Adjustable phone holder for desks.",
    price: 10.75,
    category: "Accessories",
    inStock: true,
  },
  {
    id: 15,
    name: 'Monitor 24"',
    description: "Full HD IPS monitor, 75Hz refresh rate.",
    price: 149.99,
    category: "Electronics",
    inStock: true,
  },
];

export default Products;
