const Users = [
  {
    id: 1,
    name: "Alice Johnson",
    email: "alice@example.com",
    age: 28,
    isActive: true,
  },
  {
    id: 2,
    name: "Bob Smith",
    email: "bob@example.com",
    age: 34,
    isActive: false,
  },
  {
    id: 3,
    name: "Charlie Brown",
    email: "charlie@example.com",
    age: 25,
    isActive: true,
  },
  {
    id: 4,
    name: "Diana Prince",
    email: "diana@example.com",
    age: 30,
    isActive: true,
  },
  {
    id: 5,
    name: "Ethan Hunt",
    email: "ethan@example.com",
    age: 38,
    isActive: false,
  },
  {
    id: 6,
    name: "Fiona Gallagher",
    email: "fiona@example.com",
    age: 26,
    isActive: true,
  },
  {
    id: 7,
    name: "George Martin",
    email: "george@example.com",
    age: 29,
    isActive: true,
  },
  {
    id: 8,
    name: "Hannah Lee",
    email: "hannah@example.com",
    age: 32,
    isActive: false,
  },
  {
    id: 9,
    name: "Ian Curtis",
    email: "ian@example.com",
    age: 31,
    isActive: true,
  },
  {
    id: 10,
    name: "Jane Foster",
    email: "jane@example.com",
    age: 27,
    isActive: true,
  },
  {
    id: 11,
    name: "Kevin Hart",
    email: "kevin@example.com",
    age: 40,
    isActive: false,
  },
  {
    id: 12,
    name: "Laura Palmer",
    email: "laura@example.com",
    age: 23,
    isActive: true,
  },
  {
    id: 13,
    name: "Mike Ross",
    email: "mike@example.com",
    age: 35,
    isActive: true,
  },
  {
    id: 14,
    name: "Nina Simone",
    email: "nina@example.com",
    age: 33,
    isActive: false,
  },
  {
    id: 15,
    name: "Oscar Wilde",
    email: "oscar@example.com",
    age: 29,
    isActive: true,
  },
];

export default Users;
